services:
    vertacoo_simple_news.form_factory: 
        class: Vertacoo\SimpleNewsBundle\Form\Factory\FormFactory
        arguments: ['@form.factory',"%vertacoo_simple_news.domains%","@request_stack","@translator.default"]
         
    vertacoo_simple_news.news_manager: 
        class: Vertacoo\SimpleNewsBundle\Doctrine\NewsManager
        arguments: ["@doctrine.orm.entity_manager", "%vertacoo_simple_news.entity%"]
        
        
    vertacoo_simple_news.forms.news:
        class: Vertacoo\SimpleNewsBundle\Form\Type\NewsFormType
        arguments: ["%vertacoo_simple_news.entity%","@translator.default"]
        tags:
            - { name: form.type }
            
    vertacoo_simple_news.twig.extension.news:
        class: Vertacoo\SimpleNewsBundle\Twig\NewsExtension
        tags:
             - { name: 'twig.extension' }
        arguments: ["@vertacoo_simple_news.news_manager","@vich_uploader.templating.helper.uploader_helper"]
        
    vertacoo_simple_news.form.extension.help:
        class: Vertacoo\SimpleNewsBundle\Form\Extension\HelpTypeExtension
        arguments: []
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }