services:
    Vertacoo\SimpleNewsBundle\Form\Factory\FormFactory: 
        class: Vertacoo\SimpleNewsBundle\Form\Factory\FormFactory
        arguments: ['@form.factory',"%vertacoo_simple_news.domains%","@request_stack","@translator.default"]
         
    Vertacoo\SimpleNewsBundle\Doctrine\NewsManager: 
        public: true
        autowire: true
        class: Vertacoo\SimpleNewsBundle\Doctrine\NewsManager
        arguments: ["@doctrine.orm.entity_manager", "%vertacoo_simple_news.domains%"]

        
    vertacoo_simple_news.forms.news:
        class: Vertacoo\SimpleNewsBundle\Form\Type\NewsFormType
        arguments: ["%vertacoo_simple_news.entity%","@translator.default"]
        tags:
            - { name: form.type }
            
    vertacoo_simple_news.twig.extension.news:
        class: Vertacoo\SimpleNewsBundle\Twig\NewsExtension
        tags:
             - { name: 'twig.extension' }
        arguments: ['@Vertacoo\SimpleNewsBundle\Doctrine\NewsManager','@?Vich\UploaderBundle\Templating\Helper\UploaderHelper']
        
    Vertacoo\SimpleNewsBundle\Controller\DefaultController:
        class: Vertacoo\SimpleNewsBundle\Controller\DefaultController
        public: true
        autowire: true
        tags:
             - { name: 'container.service_subscriber' }
             - { name: 'controller.service_arguments' }
