services:
     
    vertacoo_simple_news.news_manager: 
        class: Vertacoo\SimpleNewsBundle\Doctrine\NewsManager
        arguments: ["@doctrine.orm.entity_manager", "%vertacoo_simple_news.entity%"]
        
        
    vertacoo_simple_news.forms.news:
        class: "%vertacoo_simple_news.form%"
        arguments: ["%vertacoo_simple_news.entity%"]
        tags:
            - { name: form.type }
            
    vertacoo_simple_news.twig.extension.news:
        class: Vertacoo\SimpleNewsBundle\Twig\NewsExtension
        tags:
             - { name: 'twig.extension' }
        arguments: ["@vertacoo_simple_news.news_manager"]